services:
  preqin-api:
    build: ./preqin-technical-test/
    ports: 
      - 8000:8000
  
  django-app:
    build: ./preqin_investors_spa/
    ports: 
      - 8080:8080
    command: sh -c "chmod +x /app/entrypoint.sh && /app/entrypoint.sh python manage.py runserver 0.0.0.0:8080"